/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kiosk_client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    //don't worry about unit tests for now
    @Test void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest.dummyMethod(), "app should have a greeting");
    }
}
