# Generated by Django 4.1.7 on 2023-04-08 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0001_initial_squashed_0012_remove_student_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studenteventrelation",
            options={
                "ordering": ["student", "event"],
                "verbose_name": "Add Student to Event",
                "verbose_name_plural": "Add Student to Event",
            },
        ),
    ]
