# Generated by Django 4.1.7 on 2023-04-08 23:50

from django.db import migrations, models
import fbla.utils


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0013_alter_studenteventrelation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report",
            field=models.FileField(
                upload_to=fbla.utils.report_upload_path, verbose_name="Report File"
            ),
        ),
    ]
