# Generated by Django 4.2.2 on 2023-06-16 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0016_event_always_checkin_out_able_alter_event_past_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
