# Generated by Django 4.1.4 on 2023-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0017_report_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="breakdown",
            field=models.BooleanField(
                default=True,
                editable=False,
                verbose_name="Show in-depth breakdown of student points",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="graphs",
            field=models.BooleanField(
                default=True,
                editable=False,
                verbose_name="Show data distributions by grade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="winners",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Show winners of prizes"
            ),
            preserve_default=False,
        ),
    ]
