# Generated by Django 4.1.4 on 2023-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0018_report_breakdown_report_graphs_report_winners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="breakdown",
            field=models.BooleanField(
                verbose_name="Show in-depth breakdown of student points"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="graphs",
            field=models.BooleanField(verbose_name="Show data distributions by grade"),
        ),
        migrations.AlterField(
            model_name="report",
            name="winners",
            field=models.BooleanField(verbose_name="Show winners of prizes"),
        ),
    ]
