# Generated by Django 4.1.4 on 2023-06-25 21:48

from django.db import migrations, models
import fbla.utils


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0020_alter_report_breakdown_alter_report_graphs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to=fbla.utils.backup_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(
                default=False, verbose_name="Does this event recur?"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="relapse_time",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                verbose_name="How many days in between each event?",
            ),
        ),
    ]
