# Generated by Django 4.1.4 on 2023-06-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbla", "0026_alter_report_percent_of_students_at_or_below_event_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="percent_of_students_at_or_below_event_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Show % of students with <X events attended.",
            ),
        ),
    ]
